[features]
rmcp_client = true
web_search_request = true

[mcp_servers.chrome-devtools]
command = "bunx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp"

[mcp_servers.github.http_headers]
Authorization = "Bearer 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"

[mcp_servers.homebrew]
command = "brew"
args = ["mcp-server"]

[projects."/Users/chao"]
trust_level = "trusted"
